name: Update Modrinth Readme

on:
  push:
    branches:
      - main
jobs:
  update_modrinth_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install dependencies
        run: pip install requests rich
      - name: Run Python Script
        run: python .github/workflows/scripts/update_modrinth_readme.py aZhtZo3k README.md
        env:
          SECRET: ${{ secrets.MODRINTH_API_TOKEN }}